FROM golang:1.26-alpine AS tester

WORKDIR /app

RUN apk add --no-cache gcc musl-dev

# Install golangci-lint
RUN wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.6

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["sh", "-c", "go fmt ./... && go fix ./... && go test -v ./... && golangci-lint run"]
